# -*- coding: utf-8 -*-
from pathlib import Path
import json,html,re,shutil
base=Path(__file__).resolve().parent
summary=json.loads((base/'test-summary.json').read_text());source=json.loads((base/'source.json').read_text())
assets=json.loads((base/'asset-sizes.json').read_text())['assets']
prefix='artifacts/2026-10-04-deployment-admin/'
checks=[('build-final','Build всех workspaces'),('typecheck-final','Typecheck, включая E2E'),('protocol','Protocol: 23/23'),('runtime-final','Runtime: 109/109'),('sdk','SDK: 84/84'),('editor-bridge-final','Editor bridge: 86/86'),('api-http','API/PostgreSQL: 31/31 + HTTP smoke'),('browser-final',f"Browser: {summary['browser']['total']}/{summary['browser']['total']}")]
rows=''.join(f'<tr><td>{label}</td><td>PASS</td><td><a href="{prefix}{name}.log">log</a> · <a href="{prefix}{name}.json">команда и время</a></td></tr>' for name,label in checks)
images=[]
for name in ['deployment-active-mobile.png','deployment-active-desktop.png','deployment-rollback-desktop.png','deployment-admin-mobile-390.png']:
    matches=list((base/'browser-final-artifacts').glob(f'*chromium/{name}'))
    assert matches,name
    shutil.copyfile(matches[0],base/name)
    images.append(f'<figure><a href="{prefix}{name}"><img src="{prefix}{name}" alt="{html.escape(name)}" loading="lazy" style="max-width:100%;max-height:650px;border:1px solid #ddd;border-radius:8px"></a><figcaption>{name}</figcaption></figure>')
assetrows=''.join(f'<tr><td>{x["file"]}</td><td>{x["raw"]}</td><td>{x["gzip9"]}</td></tr>' for x in assets)
section=f'''<section id="SERVICE-V1-05"><span class="badge">SERVICE-V1-05 · DONE · 2026-10-05</span><h2>Публикация и ручное исправление доступны владельцу</h2>
<p>Admin различает черновик, зафиксированную версию и активную публикацию. Включение, отключение и откат требуют причины; история показывает действие, участника и время. История доступна участникам, изменять публикацию могут Owner/Admin.</p>
<ul><li>Конфликт revision перечитывает состояние и сохраняет выбор/причину. После потери ответа можно повторить ту же команду с исходным ключом. Принятый исторический ответ не выдаётся за актуальное состояние.</li><li>Проверка открывает реальный private preview. Admin проверяет popup, Origin, nonce, Page и Release; SDK отправляет только разрешённые поля диагностики из текущей PageSession, без capability или текста страницы.</li><li>Отсутствие отчёта обозначено «Не проверено». Известные ошибки и отсутствующие targets блокируют включение проверенной версии. Conditional registered/superseded остаются видимыми безопасными пропусками.</li><li>Ручной repair импортирует immutable base Release и Draft delta в один EditorSession. Новая target-repair команда заменяет прежнюю только при replay; API сохраняет delta, исходный Release неизменен. Условная группа переназначается целиком с сохранением условия и эффекта.</li><li>Мобильные переносы исправлены для длинных адресов. Пройдены переключение фокуса, клавиатурное включение, история и 390 px layout. WebKit/macOS использует Option+Tab для перехода к кнопкам.</li></ul>
<h2>Проверки окончательного среза</h2><div class="table"><table><thead><tr><th>Проверка</th><th>Результат</th><th>Evidence</th></tr></thead><tbody>{rows}</tbody></table></div>
<p><strong>302 unit + 31 API/PostgreSQL + {summary['browser']['total']} browser tests, без failed/skipped/flaky в финальных прогонах.</strong> Chromium {summary['browser']['projects']['chromium']}, Firefox {summary['browser']['projects']['firefox']}, WebKit {summary['browser']['projects']['webkit']}. Все 5 новых Admin/repair сценариев пройдены в каждом браузере. Регрессия охватывает обычную доставку, React/Vue CSR/SSR, PageSession, replay safety, auth/editor, сохранение/конфликт/undo, version/share и A/B.</p>
<p><a href="{prefix}test-summary.json">Сводка и browser cases</a> · <a href="{prefix}browser-results.json">Playwright JSON</a> · <a href="{prefix}README.md">История попыток</a>. Предыдущие неуспешные прогоны сохранены отдельно; в них обнаружены мобильный overflow, особенности клавиатуры WebKit и зависимость старых fixtures от общей Page. Данные и assertions не удалялись ради PASS.</p>
<h2>Визуальная приёмка</h2>{''.join(images)}
<h2>Размер production assets</h2><div class="table"><table><thead><tr><th>Файл</th><th>Raw bytes</th><th>Gzip 9 bytes</th></tr></thead><tbody>{assetrows}</tbody></table></div>
<p>Размеры измерены локально, <a href="{prefix}asset-sizes.json">hashes и метод</a>. Старый editor raw limit 100000 bytes всё ещё превышен. Новые бюджеты не считаются утверждёнными; performance/staging gate относится к 18.</p>
<h2>Границы результата</h2><ul><li>Отчёт относится к одному preview и хранится в открытой панели; structural fingerprint не обнаруживает CSS-only drift и не гарантирует состояние всех посетителей. Автоматического переназначения targets нет.</li><li>Технический workflow E2 выполнен локально. Внешний сервис, HTTPS staging, реальные письма и самостоятельное подтверждение домена относятся к последующим этапам. Решения 02 остаются открытыми.</li><li>Публикация требует установленного SDK с <code>delivery: 'deployment'</code>. Уже открытые вкладки получают изменение при refresh/navigation/reload; live push не добавлен. Первая версия A/B остаётся по ссылкам.</li><li>Следующая последовательная задача: SERVICE-V1-06 — регистрация независимых владельцев.</li></ul>
<h2>Идентификация среза</h2><p>HEAD <code>{source['head']}</code> + рабочие изменения; {len(source['files'])} source/config файлов; SHA-256 <code>{source['sha256']}</code>. <a href="{prefix}source.json">Манифест</a>. Build/DB/browser запускались последовательно. Внешняя публикация и коммит не выполнялись.</p></section>'''
p=base.parent.parent/'deployment.html';s=p.read_text();s=re.sub(r'<section id="SERVICE-V1-05">.*?</section>','',s,flags=re.S);s=s.replace('<section id="SERVICE-V1-04">',section+'\n<section id="SERVICE-V1-04">',1)
s=s.replace('SERVICE-V1 · Deployment API','SERVICE-V1 · Публикация и исправление').replace('E2 · 4 октября 2026','E2 · 5 октября 2026').replace('Публикация: API и SDK готовы','Публикация: Admin, SDK и API готовы').replace('Следующий шаг — управление из Admin.','Владелец управляет публикацией из Admin и вручную исправляет версию через новый черновик.')
s=s.replace('Полный E2 gate остаётся открыт: Admin Deploy/Disable/Rollback и repair — задача 05.','На момент среза 04 Admin и repair ожидали задачи 05; она завершена выше.')
s=s.replace('кнопки Admin остаются задачей 05.','кнопки Admin и repair завершены в срезе 05 выше.').replace('Полный E2 stage gate остаётся открыт.','Технический workflow E2 завершён срезом 05; общая готовность внешнего сервиса проверяется последующими этапами.')
p.write_text(s);print(p)
