import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {expect,test,required} from './fixtures';

test('named goal: test installation, consent, isolated totals and frozen launch',async({newContext},testInfo)=>{
  test.setTimeout(90_000);
  const base=required('LYKAR_E2E_API_BASE_URL'),host=required('LYKAR_E2E_PLAYGROUND_BASE_URL');
  const owner=await newContext(),visitor=await newContext(),admin=await owner.newPage();
  await admin.goto(`${base}/admin/`);await admin.getByRole('button',{name:'Войти как локальный владелец'}).click();
  await expect(admin.getByRole('heading',{name:'Northstar E2E'})).toBeVisible();
  const projects=(await (await owner.request.get(`${base}/api/admin/projects`)).json()).projects;
  const project=projects.find((p:{name:string})=>p.name==='Northstar E2E');
  expect(project).toBeTruthy();
  const id=randomUUID(),pathname=`/__e2e__/onboarding/${id}`;
  const pageResponse=await owner.request.post(`${base}/api/admin/projects/${project.id}/pages`,{data:{name:'Analytics setup',pathname}});
  expect(pageResponse.status()).toBe(201);const page=(await pageResponse.json()).page;
  const draft=(await (await owner.request.post(`${base}/api/admin/pages/${page.id}/drafts`,{data:{}})).json()).draft;
  const save=await owner.request.post(`${base}/api/admin/drafts/${draft.id}/operations`,{data:{expectedRevision:0,idempotencyKey:randomUUID(),operations:[{schemaVersion:1,id:randomUUID(),kind:'setText',target:{marker:'heading',fingerprint:{tag:'h1'}},value:'Variant B'}]}});
  expect(save.status()).toBe(200);
  const publish=await owner.request.post(`${base}/api/admin/drafts/${draft.id}/publish`,{data:{expectedRevision:1}});
  expect(publish.status()).toBe(201);const release=(await publish.json()).release;
  await writeFile(join(required('LYKAR_E2E_INSTALL_DIRECTORY'),`${id}.html`),`<!doctype html><html><head><meta name="viewport" content="width=device-width"></head><body><h1 data-lykar-id="heading">Control</h1><button id="grant">Agree</button><button id="deny">Decline</button><button id="goal">Submit lead</button><button id="other">Other action</button><output id="result"></output><script src="${host}/sdk.iife.js"></script><script>
  const sdk=window.sdk=Lykar.init('${project.publicKey}',{apiBaseUrl:'${base}',frameworkMode:'static'});
  window.ready=sdk.start();
  grant.onclick=async()=>{await sdk.consent('granted');result.textContent='granted'};
  deny.onclick=async()=>{await sdk.consent('denied');result.textContent='denied'};
  goal.onclick=async()=>{const r=await sdk.track('lead_submitted');result.textContent=r.accepted?'accepted':r.code};
  other.onclick=async()=>{await sdk.track('other_action');result.textContent='other'};
  </script></body></html>`);
  await admin.goto(`${base}/admin/?project=${project.id}&page=${page.id}&section=pages`);
  await admin.getByRole('button',{name:'Experiments',exact:true}).click();
  await expect(admin.getByRole('heading',{name:'Новый эксперимент'})).toBeVisible();
  // Exercise the actual setup UI, then keep all numerical expectations independent of implementation.
  await admin.getByLabel('Событие конверсии',{exact:true}).fill('lead_submitted');
  await admin.getByLabel('Событие конверсии',{exact:true}).press('Enter');
  const article=admin.locator('.experiment').last();
  await expect(article).toContainText('lead_submitted');
  const experiment=(await (await owner.request.get(`${base}/api/admin/pages/${page.id}/experiments`)).json()).experiments[0];
  await article.getByRole('button',{name:'Создать тестовую ссылку'}).click();
  await expect(article.getByRole('link',{name:'Открыть тестовую ссылку'})).toBeVisible();
  const probeUrl=await article.getByRole('link',{name:'Открыть тестовую ссылку'}).getAttribute('href');
  const probe={url:probeUrl!};
  const refreshDiagnostic=async()=>{await article.getByRole('button',{name:'Обновить диагностику'}).click();await expect(article.getByRole('button',{name:'Обновить диагностику'})).toBeEnabled();};
  const report=async()=> (await (await owner.request.get(`${base}/api/admin/experiments/${experiment.id}/analytics`)).json()).report;
  let browser=await visitor.newPage();await browser.goto(probe.url);await browser.evaluate(()=> (window as any).ready);
  await refreshDiagnostic();await expect(article).toContainText('ожидается решение');
  await browser.getByRole('button',{name:'Submit lead'}).click();await expect(browser.locator('#result')).toHaveText('CONSENT_REQUIRED');
  await browser.getByRole('button',{name:'Decline'}).click();await expect(browser.locator('#result')).toHaveText('denied');await refreshDiagnostic();await expect(article).toContainText('пользователь отказал');
  await browser.getByRole('button',{name:'Submit lead'}).click();await expect(browser.locator('#result')).toHaveText('CONSENT_DENIED');
  await browser.getByRole('button',{name:'Agree'}).click();await expect(browser.locator('#result')).toHaveText('granted');await refreshDiagnostic();await expect(article).toContainText('выбранное событие ещё не поступило');
  await browser.getByRole('button',{name:'Submit lead'}).click();await expect(browser.locator('#result')).toHaveText('accepted');await refreshDiagnostic();await expect(article).toContainText('Успех: выбранное событие получено.');
  await article.getByText('Инструкция SDK / script: событие и согласие',{exact:true}).click();
  await admin.screenshot({path:testInfo.outputPath('analytics-test-desktop.png'),fullPage:true});
  expect((await report()).variants.map((v:any)=>[v.visitors,v.views,v.conversions])).toEqual([[0,0,0],[0,0,0]]);
  const launch=await owner.request.post(`${base}/api/admin/experiments/${experiment.id}/activate`,{data:{}});expect(launch.ok()).toBeTruthy();
  const linkResponse=await owner.request.post(`${base}/api/admin/experiments/${experiment.id}/links`,{data:{}});expect(linkResponse.status()).toBe(201);
  await browser.close();browser=await visitor.newPage();
  await browser.goto((await linkResponse.json()).url);await browser.evaluate(()=> (window as any).ready);
  expect((await report()).variants.reduce((n:number,v:any)=>n+v.views,0)).toBe(0);
  await browser.getByRole('button',{name:'Agree'}).click();await expect(browser.locator('#result')).toHaveText('granted');
  await browser.getByRole('button',{name:'Submit lead'}).click();await expect(browser.locator('#result')).toHaveText('accepted');
  await browser.getByRole('button',{name:'Other action'}).click();await expect(browser.locator('#result')).toHaveText('other');
  await browser.getByRole('button',{name:'Submit lead'}).click();await expect(browser.locator('#result')).toHaveText('accepted');
  const selected=await report();expect(selected.conversionEventName).toBe('lead_submitted');
  expect(selected.variants.reduce((n:number,v:any)=>n+v.visitors,0)).toBe(1);
  expect(selected.variants.reduce((n:number,v:any)=>n+v.views,0)).toBe(1);
  expect(selected.variants.reduce((n:number,v:any)=>n+v.uniqueConversions,0)).toBe(1);
  expect(selected.variants.reduce((n:number,v:any)=>n+v.conversions,0)).toBe(2);
  await browser.evaluate(()=> (window as any).sdk.refresh());
  expect((await report()).variants.reduce((n:number,v:any)=>n+v.views,0)).toBe(1);
  await browser.getByRole('button',{name:'Decline'}).click();await browser.getByRole('button',{name:'Submit lead'}).click();
  expect((await report()).variants.reduce((n:number,v:any)=>n+v.conversions,0)).toBe(2);
  await admin.reload();await admin.getByRole('button',{name:'Experiments',exact:true}).click();await expect(admin.locator('.experiment')).toContainText('lead_submitted');
  await admin.locator('.experiment').getByRole('button',{name:'Показать аналитику'}).click();
  await expect(admin.locator('.analytics-report')).toContainText('lead_submitted');
  await admin.setViewportSize({width:390,height:844});
  expect(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await admin.screenshot({path:testInfo.outputPath('analytics-mobile.png'),fullPage:true});
});
