import {join} from 'node:path';
import {readFile,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {test,expect,required} from './fixtures';

for(const mobile of [false,true]) test(`new customer installs copied snippet and saves first preview (${mobile?'mobile keyboard':'desktop'})`,async({newContext},testInfo)=>{
  test.setTimeout(60000);
  const base=required('LYKAR_E2E_API_BASE_URL'),origin=required('LYKAR_E2E_PLAYGROUND_BASE_URL');
  const context=await newContext(),admin=await context.newPage();
  await admin.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:960});
  const email=`onboarding-${randomUUID()}@example.com`;
  await admin.goto(`${base}/admin/`);
  await admin.getByLabel('Email',{exact:true}).fill(email);
  await admin.getByLabel('Email',{exact:true}).press('Enter');
  await expect(admin.getByText('Проверьте почту.',{exact:false})).toBeVisible();
  let magic='';
  await expect.poll(async()=>{const lines=(await readFile(required('LYKAR_E2E_MAGIC_LINK_FILE'),'utf8')).trim().split('\n').map(line=>JSON.parse(line));magic=lines.findLast(line=>line.email===email)?.url??'';return Boolean(magic);}).toBe(true);
  await admin.goto(magic);
  await admin.getByPlaceholder('Название',{exact:true}).fill('Новый сайт onboarding');
  await admin.getByPlaceholder('https://example.com',{exact:true}).fill(origin);
  await admin.getByPlaceholder('https://example.com',{exact:true}).press('Enter');
  await expect(admin.getByRole('heading',{name:'От сайта до первой правки'})).toBeVisible();
  await admin.getByRole('button',{name:'Подтвердить localhost'}).click();
  await expect(admin.getByText('Локальный адрес подтверждён.',{exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Далее: Установить SDK'}).click();
  await expect(admin.getByLabel('Персональная инструкция установки Lykar')).toBeVisible();
  await admin.reload();
  const instruction=admin.getByLabel('Персональная инструкция установки Lykar');
  await expect(instruction).toBeVisible();
  const snippet=await instruction.inputValue();
  expect(snippet).toContain(base);expect(snippet).toContain("frameworkMode: 'static'");expect(snippet).not.toContain('pk_playground_local');
  const installedId=randomUUID(),pathname=`/__e2e__/onboarding/${installedId}`;
  // The customer-owned HTML receives the exact UI-generated snippet; SDK/API/assets remain real.
  const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1 id="customer-heading">Мой первый заголовок</h1>${snippet}</body></html>`;
  await writeFile(join(required('LYKAR_E2E_INSTALL_DIRECTORY'),`${installedId}.html`),html);
  const copy=admin.getByRole('button',{name:'Скопировать код установки'});await copy.focus();await admin.keyboard.press('Enter');
  await expect(admin.getByRole('status').filter({hasText:/Инструкция скопирована|Текст выделен/})).toBeVisible();
  await admin.getByRole('button',{name:'Страницы',exact:true}).click();
  await admin.getByLabel('Название страницы').fill('Моя страница');await admin.getByLabel('Путь страницы').fill(pathname);await admin.getByRole('button',{name:'Добавить',exact:true}).click();
  await admin.getByRole('button',{name:`Моя страница ${pathname}`,exact:true}).click();
  await admin.getByRole('button',{name:'Мастер подключения',exact:true}).click();
  await admin.getByRole('button',{name:'Далее: Проверить страницу'}).click();
  await admin.getByRole('button',{name:'Проверить подключение',exact:true}).click();
  await expect(admin.getByText('Проверка завершена:',{exact:false})).toBeVisible({timeout:20000});
  await admin.screenshot({path:testInfo.outputPath(`onboarding-connection-${mobile?'mobile':'desktop'}.png`),fullPage:true});
  const overflow=await admin.evaluate(()=>({width:innerWidth,actual:document.documentElement.scrollWidth,elements:Array.from(document.querySelectorAll('body *')).filter(el=>el.getBoundingClientRect().right>innerWidth+1||el.scrollWidth>el.clientWidth+1).slice(0,12).map(el=>({tag:el.tagName,cls:el.className,scroll:el.scrollWidth,client:el.clientWidth,width:el.getBoundingClientRect().width,text:el.textContent?.slice(0,80)}))}));
  expect(overflow.actual,JSON.stringify(overflow)).toBeLessThanOrEqual(overflow.width);
  await admin.getByRole('button',{name:'Далее: Первая правка'}).click();
  await admin.getByRole('button',{name:'Создать черновик',exact:true}).click();
  const popup=context.waitForEvent('page');await admin.getByRole('button',{name:'Открыть редактор',exact:true}).click();const editor=await popup;
  const panel=editor.locator('[data-lykar-editor-root="panel"]');
  await expect(panel.getByRole('heading',{name:'Lykar Editor'})).toBeVisible();
  await editor.locator('#customer-heading').click();await panel.locator('[data-field="text"]').fill('Моя первая сохранённая правка');
  await panel.locator('[data-action="apply"]').click();
  await expect(panel.locator('[data-field="status"]')).toContainText('Сохранено команд: 1');
  await editor.reload();await expect(editor.locator('#customer-heading')).toHaveText('Моя первая сохранённая правка');
  await editor.close();await admin.reload();
  await admin.getByRole('button',{name:'Зафиксировать версию',exact:true}).click();
  await admin.getByRole('button',{name:'Ссылка на версию',exact:true}).click();
  const share=await admin.getByLabel('Share URL').inputValue();
  const preview=await context.newPage();await preview.goto(share);
  await expect(preview.locator('#customer-heading')).toHaveText('Моя первая сохранённая правка');
  await expect(preview.locator('[data-lykar-editor-root="panel"]')).toHaveCount(0);
  await preview.screenshot({path:testInfo.outputPath('onboarding-first-preview.png')});
  await admin.screenshot({path:testInfo.outputPath(`onboarding-finished-${mobile?'mobile':'desktop'}.png`),fullPage:true,mask:[admin.getByLabel('Share URL')]});
});

test('manual pages, origin management and selected sitemap preview stay in the current project',async({newContext})=>{
  const base=required('LYKAR_E2E_API_BASE_URL'),context=await newContext(),admin=await context.newPage();
  await admin.goto(`${base}/admin/`);
  const email=`sitemap-ui-${randomUUID()}@example.com`;
  await admin.getByLabel('Email',{exact:true}).fill(email);await admin.getByLabel('Email',{exact:true}).press('Enter');
  await expect(admin.getByText('Проверьте почту.',{exact:false})).toBeVisible();
  let magic='';await expect.poll(async()=>{const lines=(await readFile(required('LYKAR_E2E_MAGIC_LINK_FILE'),'utf8')).trim().split('\n').map(line=>JSON.parse(line));magic=lines.findLast(line=>line.email===email)?.url??'';return Boolean(magic);}).toBe(true);
  await admin.goto(magic);
  const origin=`https://onboarding-${randomUUID()}.example.com`;
  await admin.getByPlaceholder('Название',{exact:true}).fill('Sitemap onboarding');await admin.getByPlaceholder('https://example.com',{exact:true}).fill(origin);await admin.getByRole('button',{name:'Создать',exact:true}).click();
  await admin.getByLabel('Дополнительный адрес').fill(`https://www.${new URL(origin).hostname}`);await admin.getByRole('button',{name:'Добавить адрес',exact:true}).click();
  const remove=admin.getByRole('button',{name:`Удалить https://www.${new URL(origin).hostname}`,exact:true});await expect(remove).toBeVisible();await remove.click();await expect(remove).toHaveCount(0);
  await admin.getByRole('button',{name:'Страницы',exact:true}).click();
  await admin.getByLabel('Название страницы').fill('Ручная страница');await admin.getByLabel('Путь страницы').fill('/manual');await admin.getByRole('button',{name:'Добавить',exact:true}).click();
  await expect(admin.getByRole('button',{name:'Ручная страница /manual',exact:true})).toBeVisible();
  await admin.getByText('Импортировать страницы из sitemap',{exact:true}).click();
  await admin.getByLabel('URL sitemap').fill(`${origin}/sitemap.xml`);
  // UI preview is deterministic; transport/parser and current-allowlist checks have API coverage.
  await admin.route('**/sitemap/preview',route=>route.fulfill({json:{pages:[{url:`${origin}/manual`,pathname:'/manual'},{url:`${origin}/new`,pathname:'/new'},{url:`${origin}/skip`,pathname:'/skip'}],duplicates:1,excluded:1}}));
  await admin.getByRole('button',{name:'Предпросмотр sitemap'}).click();
  await admin.getByLabel('/skip',{exact:true}).uncheck();await admin.getByRole('button',{name:'Импортировать выбранные (2)',exact:true}).click();
  await expect(admin.getByRole('button',{name:'/new /new',exact:true})).toBeVisible();await expect(admin.getByRole('button',{name:'/skip /skip',exact:true})).toHaveCount(0);
  await admin.reload();await expect(admin.getByRole('button',{name:'Ручная страница /manual',exact:true})).toHaveCount(1);
});
