from pathlib import Path
import json, re, html
base=Path(__file__).resolve().parent
read=lambda name:json.loads((base/name).read_text())
source=read('source.json'); tests=read('test-summary.json'); assets=read('asset-sizes.json')['assets']
prefix='artifacts/2026-10-04-deployment-delivery/'
checks=[('build','Общий build'),('typecheck-final','Общий typecheck, включая E2E'),('runtime-complete','Runtime: 106/106'),('sdk-complete','SDK: 62/62'),('browser-regression','Browser: 55/55')]
rows=[]
for name,label in checks:
 result=read(name+'.json')
 assert result['code']==0,name
 rows.append(f'<tr><td>{label}</td><td>PASS</td><td><a href="{prefix}{name}.log">log</a> · <a href="{prefix}{name}.json">команда / timestamps</a></td></tr>')
asset_rows=''.join(f'<tr><td>{a["file"].split("/")[-1]}</td><td>{a["raw"]}</td><td>{a["gzip9"]}</td></tr>' for a in assets)
cases=''.join(f'<li>{html.escape(c["title"])}</li>' for c in tests['browser']['cases'] if c['file']=='deployment-flow.spec.ts' and c['project']=='chromium')
section=f'''<section id="SERVICE-V1-04"><span class="badge">SERVICE-V1-04 · DONE · 2026-10-04</span><h2>Активная версия доставляется через SDK</h2>
<p>При <code>delivery: 'deployment'</code> обычный посетитель получает текущий Release своей Page. Publish только фиксирует версию; Deploy включает её, Disable возвращает исходную страницу, Rollback выбирает ранее активированный Release.</p>
<ul><li>Анонимный GET с <code>credentials: omit</code> и <code>cache: no-store</code>. API проверяет Origin. Deployment не отправляет analytics и не загружает editor.</li><li>Повторный start использует ту же generation. Refresh, navigation и reload снимают прежние правки и перечитывают pointer. Вкладка не получает live push.</li><li>Editor, share, version и A/B selectors изолированы. Native A остаётся исходной страницей при активном deployment. Пустые, повторные и конфликтующие selectors дают диагностику без fallback.</li><li>Сетевые ошибки и invalid payload оставляют исходную страницу. SDK deadline охватывает fetch и тело ответа, даже если transport игнорирует abort. Старый ответ не меняет новую Page.</li><li>Частичная ошибка компенсирует обычные операции и условные overlays; новые изменения самого host сохраняются. Initial unsafe conditional target завершает replay отказом. Missing/not-ready/inactive остаются отложенными состояниями существующего S4-контракта.</li><li>Metadata: <code>runtime.deployment</code>; при partial apply — <code>runtime.report</code>. Диагностика показывает снятые операции, а не успешное применение.</li></ul>
<h2>Проверки окончательного среза</h2><div class="table"><table><thead><tr><th>Проверка</th><th>Результат</th><th>Evidence</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div>
<p><strong>168 unit + 55 browser tests, без failed/skipped/flaky.</strong> Browser: Chromium 23, Firefox 16, WebKit 16; 24 новых deployment cases. Временная PostgreSQL/API создаётся, мигрируется и удаляется harness; общий стенд использован последовательно. Последний browser harness пересобрал финальные SDK/runtime/fixtures; после него выполнен общий typecheck. <a href="{prefix}test-summary.json">Имена и статусы</a> · <a href="{prefix}browser-results.json">Playwright JSON</a> · <a href="{prefix}runtime-complete-results.json">Runtime JSON</a> · <a href="{prefix}sdk-complete-results.json">SDK JSON</a>.</p>
<ul>{cases}</ul>
<p>Регрессия: PageSession lifecycle, replay safety, S4 conditional/SPA/hydration, S3 A/B, auth/editor и versioning/share. API/PostgreSQL 31/31 и HTTP smoke подтверждены отдельным срезом 03 ниже; полный API suite в 04 повторно не запускался, серверный код не менялся.</p>
<h2>Размер артефактов</h2><div class="table"><table><thead><tr><th>Файл</th><th>Raw bytes</th><th>Gzip level 9 bytes</th></tr></thead><tbody>{asset_rows}</tbody></table></div>
<p>Локальный production build, gzip через Python/zlib. Initial script bootstrap укладывается в прежние 80000/25000 bytes. Combined bootstrap/runtime и editor оцениваются отдельно; новые D04 бюджеты остаются PROPOSED. Старый editor raw limit 100000 по-прежнему превышен. HTTPS staging latency/CLS и performance gate относятся к 18. <a href="{prefix}asset-sizes.json">Размеры и hashes</a>.</p>
<h2>Предыдущие попытки и ограничения</h2><ul><li>Первый параллельный runtime run не поднял workers вовремя; последовательный run прошёл. Это инфраструктурный failure, не выданный за PASS.</li><li>Первый browser run: 15 PASS / 6 FAIL. Слишком широкий test selector считал служебный playground block редактором и прерывал очистку active Experiment. После исправления test selector: 21/21, затем финальная расширенная regression 55/55. <a href="{prefix}browser-deployment.log">Первый log</a>; screenshot/trace/video сохранены в <code>browser-artifacts/</code>.</li><li>Новый unit fixture unsafe conditional был исправлен: ему нужен ready framework root только вокруг условных targets. Финальный тест подтверждает компенсацию обычного текста и уже активного conditional overlay.</li><li>Transport faults детерминированно вводятся в браузере и unit: reject, HTTP failure, hanging fetch/body и late response. Это не проверка внешней сети и не staging SLA.</li><li>Существующие отдельные defaults сохранены: network 5000 ms, replay 2000 ms, lazy runtime asset load 10000 ms. Предлагаемый D03 network 2000 ms не внедрён. Low-level runtime получает caller-owned fetch/signal; ограничение сети реализует SDK.</li><li>Полный E2 gate остаётся открыт: Admin Deploy/Disable/Rollback и repair — задача 05. Подтверждение домена пользователем — 08, инфраструктура и новые budgets — 02/12/18. Внешняя публикация не выполнялась.</li></ul>
<h2>Идентификация</h2><p>HEAD <code>{source['head']}</code> + рабочие изменения. SHA-256 <code>{source['sha256']}</code>, {len(source['files'])} файлов. <a href="{prefix}source.json">Source manifest и метод hash</a> · <a href="../../../../packages/sdk/README.md#explicit-deployment-delivery">SDK-контракт</a>.</p></section>'''
p=base.parent.parent/'deployment.html';s=p.read_text()
s=re.sub(r'<section id="SERVICE-V1-04">.*?</section>','',s,flags=re.S)
s=s.replace('<section id="SERVICE-V1-03">',section+'\n<section id="SERVICE-V1-03">',1)
s=s.replace('E2 · 3 октября 2026','E2 · 4 октября 2026').replace('Публикация: backend готов','Публикация: API и SDK готовы')
s=s.replace('Подключение к SDK и Admin остаётся следующей частью E2.','SDK применяет активную версию, корректно отключает и откатывает её. Следующий шаг — управление из Admin.')
s=s.replace('SDK пока не вызывает новый endpoint, Admin пока не содержит кнопок deployment. Обычный сайт этим backend-срезом ещё не меняется.', 'На момент завершения backend 03 SDK ещё не вызывал endpoint. Интеграция выполнена в срезе 04 выше; кнопки Admin остаются задачей 05.')
s=s.replace('Browser deployment/SPA/failure matrix относится к 04; она здесь не выдаётся за выполненную.', 'Browser deployment/SPA/failure matrix подтверждена срезом 04 выше; API-срез 03 имел отдельную проверку.')
p.write_text(s)
print(p)
